### ISSUE TITLE
Pls explain the development approach

### ISSUE THREAD

**Issue by blackgwe** [dragoscirjan/aurelia-material-components-web#2]
How does your development approach differ / where do you see the advantages e.g. compared to
* https://github.com/Ullfis/aurelia-mdc-bridge
* https://ullfis.github.io/aurelia-mdc-bridge/#/components/buttons

**Comment by dragoscirjan** [comment]
@blackgwe well... for once, mine is incomplete :yum: 

Now, leaving the jokes aside, it's quite amazing that you find this project, considering the fact that I've been looking a lot before starting it and the only relevant one I found was [aurelia-mdc-plugin](https://github.com/arabsight/aurelia-mdc-plugin/), which is only a wrapper, not creating dedicated aurelia components.

Otherwise, I guess the approach is almost the same with Ullfis' [aurelia-mdc-bridge](https://github.com/Ullfis/aurelia-mdc-bridge). Maybe just the level of detail. See https://github.com/Ullfis/aurelia-mdc-bridge/tree/master/src/components/cards vs https://github.com/dragoscirjan/aurelia-material-components-web/blob/master/src/card.js

You gave me a good repository to study. I do need to discover how he managed to use `@inject(Element)` on a `@containerless` component.

**Comment by blackgwe** [comment]
Thank you for your response!!!
